"""empty message

Revision ID: 3ee35f5125d3
Revises: b5cd4f6cc0a0
Create Date: 2020-05-28 18:02:58.033197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee35f5125d3'
down_revision = 'b5cd4f6cc0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('phase', sa.Integer(), nullable=False))
    op.add_column('material', sa.Column('work_id', sa.String(length=130), nullable=False))
    op.create_foreign_key(None, 'material', 'work', ['work_id', 'phase'], ['id', 'phase'])
    op.add_column('size', sa.Column('phase', sa.Integer(), nullable=False))
    op.add_column('size', sa.Column('work_id', sa.String(length=130), nullable=False))
    op.create_foreign_key(None, 'size', 'work', ['work_id', 'phase'], ['id', 'phase'])
    op.drop_constraint('work_size_id_fkey', 'work', type_='foreignkey')
    op.drop_constraint('work_material_id_fkey', 'work', type_='foreignkey')
    op.drop_column('work', 'material_id')
    op.drop_column('work', 'size_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('size_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('work', sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('work_material_id_fkey', 'work', 'material', ['material_id'], ['id'])
    op.create_foreign_key('work_size_id_fkey', 'work', 'size', ['size_id'], ['id'])
    op.drop_constraint(None, 'size', type_='foreignkey')
    op.drop_column('size', 'work_id')
    op.drop_column('size', 'phase')
    op.drop_constraint(None, 'material', type_='foreignkey')
    op.drop_column('material', 'work_id')
    op.drop_column('material', 'phase')
    # ### end Alembic commands ###
