"""empty message

Revision ID: b5cd4f6cc0a0
Revises: 94e50109fe8b
Create Date: 2020-05-28 17:53:39.046066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cd4f6cc0a0'
down_revision = '94e50109fe8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('phase', sa.Integer(), nullable=False))
    op.add_column('material', sa.Column('work_id', sa.String(length=130), nullable=False))
    op.create_foreign_key(None, 'material', 'work', ['work_id', 'phase'], ['id', 'phase'])
    op.add_column('sale', sa.Column('work_id', sa.String(length=130), nullable=True))
    op.create_foreign_key(None, 'sale', 'work', ['work_id'], ['id'])
    op.add_column('size', sa.Column('phase', sa.Integer(), nullable=False))
    op.add_column('size', sa.Column('work_id', sa.String(length=130), nullable=False))
    op.create_foreign_key(None, 'size', 'work', ['work_id', 'phase'], ['id', 'phase'])
    op.drop_constraint('work_material_id_fkey', 'work', type_='foreignkey')
    op.drop_constraint('work_size_id_fkey', 'work', type_='foreignkey')
    op.drop_column('work', 'material_id')
    op.drop_column('work', 'size_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('size_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('work', sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('work_size_id_fkey', 'work', 'size', ['size_id'], ['id'])
    op.create_foreign_key('work_material_id_fkey', 'work', 'material', ['material_id'], ['id'])
    op.drop_constraint(None, 'size', type_='foreignkey')
    op.drop_column('size', 'work_id')
    op.drop_column('size', 'phase')
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_column('sale', 'work_id')
    op.drop_constraint(None, 'material', type_='foreignkey')
    op.drop_column('material', 'work_id')
    op.drop_column('material', 'phase')
    # ### end Alembic commands ###
